package CardInfo.model.entity;
// Generated 2016-4-19 12:40:33 by Hibernate Tools 3.4.0.CR1

/**
 * SscardInfo generated by hbm2java
 */
public class SscardInfo implements java.io.Serializable {
	private static final long serialVersionUID = -7129304113317364827L;
	private Integer id;
	private String idNum;
	private String sscardNum;
	private String userName;
	private Byte sscardCondition;

	public SscardInfo() {
	}

	public SscardInfo(Integer id, String idNum, String sscardNum, String userName, Byte sscardCondition) {
		this.id = id;
		this.idNum = idNum;
		this.sscardNum = sscardNum;
		this.userName = userName;
		this.sscardCondition = sscardCondition;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getIdNum() {
		return this.idNum;
	}

	public void setIdNum(String idNum) {
		this.idNum = idNum;
	}

	public String getSscardNum() {
		return this.sscardNum;
	}

	public void setSscardNum(String sscardNum) {
		this.sscardNum = sscardNum;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Byte getSscardCondition() {
		return sscardCondition;
	}

	public void setSscardCondition(Byte sscardCondition) {
		this.sscardCondition = sscardCondition;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	
}
