package CardInfo.model.entity;
// Generated 2016-4-15 15:29:12 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TCardInfo generated by hbm2java
 */
public class TCardInfo implements java.io.Serializable {
	private static final long serialVersionUID = -2795502884114517278L;
	private String fdid;
	private String cardno;
	private String registryno;
	private Date creatcardtime;
	private String creatcardhospcode;
	private String creatcardhospname;
	private Date receivetime;
	private Short isblacklist;
	private Date reportlosttime;
	private Short cardtype;
	private String remark;
	private BigDecimal balance;
	private String username;
	private String idtype;
	private String idno;
	private String qrcode;
	private Date reportbacktime;
	private String userId;
	private String openId;
	private String sscardno;
	private String appUserid;

	public TCardInfo() {
	}

	public TCardInfo(String fdid, String cardno, Date creatcardtime, Date receivetime, Date reportlosttime,
			String userId) {
		this.fdid = fdid;
		this.cardno = cardno;
		this.creatcardtime = creatcardtime;
		this.receivetime = receivetime;
		this.reportlosttime = reportlosttime;
		this.userId = userId;
	}

	public TCardInfo(String fdid, String cardno, String registryno, Date creatcardtime, String creatcardhospcode,
			String creatcardhospname, Date receivetime, Short isblacklist, Date reportlosttime, Short cardtype,
			String remark, BigDecimal balance, String username, String idtype, String idno, String qrcode,
			Date reportbacktime, String userId, String openId, String sscardno, String appUserid) {
		this.fdid = fdid;
		this.cardno = cardno;
		this.registryno = registryno;
		this.creatcardtime = creatcardtime;
		this.creatcardhospcode = creatcardhospcode;
		this.creatcardhospname = creatcardhospname;
		this.receivetime = receivetime;
		this.isblacklist = isblacklist;
		this.reportlosttime = reportlosttime;
		this.cardtype = cardtype;
		this.remark = remark;
		this.balance = balance;
		this.username = username;
		this.idtype = idtype;
		this.idno = idno;
		this.qrcode = qrcode;
		this.reportbacktime = reportbacktime;
		this.userId = userId;
		this.openId = openId;
		this.sscardno = sscardno;
		this.appUserid = appUserid;
	}

	public String getFdid() {
		return this.fdid;
	}

	public void setFdid(String fdid) {
		this.fdid = fdid;
	}

	public String getCardno() {
		return this.cardno;
	}

	public void setCardno(String cardno) {
		this.cardno = cardno;
	}

	public String getRegistryno() {
		return this.registryno;
	}

	public void setRegistryno(String registryno) {
		this.registryno = registryno;
	}

	public Date getCreatcardtime() {
		return this.creatcardtime;
	}

	public void setCreatcardtime(Date creatcardtime) {
		this.creatcardtime = creatcardtime;
	}

	public String getCreatcardhospcode() {
		return this.creatcardhospcode;
	}

	public void setCreatcardhospcode(String creatcardhospcode) {
		this.creatcardhospcode = creatcardhospcode;
	}

	public String getCreatcardhospname() {
		return this.creatcardhospname;
	}

	public void setCreatcardhospname(String creatcardhospname) {
		this.creatcardhospname = creatcardhospname;
	}

	public Date getReceivetime() {
		return this.receivetime;
	}

	public void setReceivetime(Date receivetime) {
		this.receivetime = receivetime;
	}

	public Short getIsblacklist() {
		return this.isblacklist;
	}

	public void setIsblacklist(Short isblacklist) {
		this.isblacklist = isblacklist;
	}

	public Date getReportlosttime() {
		return this.reportlosttime;
	}

	public void setReportlosttime(Date reportlosttime) {
		this.reportlosttime = reportlosttime;
	}

	public Short getCardtype() {
		return this.cardtype;
	}

	public void setCardtype(Short cardtype) {
		this.cardtype = cardtype;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public BigDecimal getBalance() {
		return this.balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getIdtype() {
		return this.idtype;
	}

	public void setIdtype(String idtype) {
		this.idtype = idtype;
	}

	public String getIdno() {
		return this.idno;
	}

	public void setIdno(String idno) {
		this.idno = idno;
	}

	public String getQrcode() {
		return this.qrcode;
	}

	public void setQrcode(String qrcode) {
		this.qrcode = qrcode;
	}

	public Date getReportbacktime() {
		return this.reportbacktime;
	}

	public void setReportbacktime(Date reportbacktime) {
		this.reportbacktime = reportbacktime;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getOpenId() {
		return this.openId;
	}

	public void setOpenId(String openId) {
		this.openId = openId;
	}

	public String getSscardno() {
		return this.sscardno;
	}

	public void setSscardno(String sscardno) {
		this.sscardno = sscardno;
	}

	public String getAppUserid() {
		return this.appUserid;
	}

	public void setAppUserid(String appUserid) {
		this.appUserid = appUserid;
	}

}
